Feature/editions reserve button
danskernesdigitalebibliotek/dpl-react pull request #112
Opened 2022-08-30 14:33 UTC by Adamik10

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-202

#### Description
In this PR we make sure to show the correct reservation button on each individual edition on the work page. 

#### Screenshot of the result 
![image](https://user-images.githubusercontent.com/28546954/187458384-0ce67c7a-9a41-4a51-8973-c05318b09fa5.png)

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions
n/a

2022-09-05 11:48 UTC, Adamik10 commented on src/components/material/material-buttons/physical/MaterialButtonPhysical.tsx
> +        onClick={() => {
Good point :)

2022-09-06 13:25 UTC, kasperg requested changes
:+1: LGTM. There are a few things I would like you to look into.

2022-09-06 14:34 UTC, Adamik10 commented on src/components/material/material-buttons/MaterialButtons.tsx
> +  size?: "large" | "medium" | "small" | "xsmall";
Great comment! :) done

2022-09-06 14:39 UTC, Adamik10 commented on src/components/material/material-buttons/physical/MaterialButtonsFindOnShelf.tsx
> +  faustIds: string[];
Done! :) makes sense, thanks for suggesting it.

2022-09-06 14:47 UTC, Adamik10 commented on src/components/material/material-buttons/physical/MaterialButtonsFindOnShelf.tsx
> +      className="link-tag text-small-caption material-manifestation-item__find capitalize-all"
yes ;)

2022-09-08 07:30 UTC, sinejespersen approved these changes

2022-09-09 08:54 UTC, merged