Add "location" and "sublocation" URL parameters in advanced search (CQL)
danskernesdigitalebibliotek/dpl-react pull request #1440
Opened 2024-09-18 11:10 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFHER-76

#### Description

This pull request implements URL parameters for `location` and `sublocation`. Additionally, the parameters from the URL are processed in `useEffectOnce`, ensuring they are included on the first load. The `removeQueryParametersFromUrl` function is used to remove the parameters if their strings are empty.

2024-09-30 08:30 UTC, kasperbirch1 commented on src/apps/advanced-search/CqlSearchHeader.tsx
>          label="Location"
Rember translation

2024-09-30 08:30 UTC, kasperbirch1 commented on src/apps/advanced-search/CqlSearchHeader.tsx
>          label="Sublocation"
And here

2024-10-01 08:58 UTC, kasperg requested changes
:+1: This seems to work well.

I am not totally satisfied about the code structure in advanced search in the way we handle url parameters etc. but that is none of your fault. The implementation follows what is.

I have a few comments regarding the code structure of the next form components.

I appreciate the updated design for the form elements. I think the form looks better.
Consider if they take up too much vertical space between the title and the form.

<img width="2551" alt="Monosnap | DPL CMS 2024-10-01 10-53-36" src="https://github.com/user-attachments/assets/6c1be72b-a13e-4369-89f3-2967a70b461e">

As I see it some of the issue is caused by different approaches in the "normal" form and in the CQL form. One uses margins. The other grip/gap.

2024-10-01 08:58 UTC, kasperg commented on src/apps/advanced-search/CqlSearchHeader.tsx
> +        name="name"
Please exclude `name` if it is not necessary.

It is not something we use for the other form components like `TextInput`. 

I do not think the current value provides any meaning either.

2024-10-01 08:58 UTC, kasperg commented on src/components/forms/label/Label.tsx
> +const Label: FC<LabelProps> = ({ id, className, children }) => (
:+1: for adding this to be used with the `Textarea` component.

However I think it is a problem that we do not use it within the current `TextInput` component which served a similar purpose.

I suggest that you either use the new `Label` component both places or drop it for now and fall back to a simple `<label>` element.

2024-10-01 08:58 UTC, kasperg commented on src/components/forms/textarea/Textarea.tsx
Please consider the location of this component (and `Label`).

This creares a new `forms` directory` but we already have `TextInput` recide within `atoms/input`.

Either move this component within input or move `TextInput` into `forms`.

2024-10-01 09:15 UTC, kasperbirch1 commented on src/components/forms/textarea/Textarea.tsx
I want to move it to reflect the folder structure in dpl-design-system

2024-10-01 10:10 UTC, kasperbirch1 commented on .storybook/preview.js
> +  (Story) => (
This was a Prettier (format on save) change. However, it should be the same result.

2024-10-01 11:27 UTC, kasperg approved these changes

2024-10-01 11:37 UTC, merged