Change interestPeriod for a reservation
danskernesdigitalebibliotek/dpl-react pull request #159
Opened 2022-09-22 10:00 UTC by kasperbirch1

#### https://reload.atlassian.net/browse/DDFSOEG-211

#### This PR adds the possibility to change the InterestPeriod for a reservation 

The following is added: 
- NoInterestAfterModal
- getFutureDateString 
Returns a string (YYYY-MM-DD)
- move getNoInterestAfter to reservation/helper.ts
- add translations 

#### Screenshot of the result
<img width="1728" alt="Skærmbillede 2022-09-22 kl  14 29 39" src="https://user-images.githubusercontent.com/49920322/191747468-2bcf5232-d142-4e81-a207-5311048b2dab.png">
<img width="1728" alt="Skærmbillede 2022-09-22 kl  14 29 45" src="https://user-images.githubusercontent.com/49920322/191747489-f81572af-5ebb-4aee-a6d9-01769bbc8e65.png">
<img width="747" alt="Skærmbillede 2022-09-22 kl  14 30 37" src="https://user-images.githubusercontent.com/49920322/191747521-f28d49d4-d8c4-4be6-9ab6-8e90acb209a6.png">

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2022-09-26 08:37 UTC, kasperg requested changes
:+1: Good stuff here. Please look into your type handling for interest dates.

2022-09-26 08:37 UTC, kasperg commented on src/components/reservation/helper.ts
> +  days: number | string,
Please look into how we can limit the types we access for our internal functions. A number of days should only be in the form of a number - not a string which may contain a number or not.

The fact that JavaScript object cannot have numeric keys is an implementation detail.

2022-09-26 08:37 UTC, kasperg commented on src/components/reservation/helper.ts
> +};
Please rework this function.

Our internal representation of the users interest date should be a number of days wherever possible. Not a string.

When working with dates where the standard JavaScript date api does not help us much (outputting a date in a specific format, modifying a date) we use `Day.js`. It provides helpful methods e.g. [`format()`] and [`add()'](https://day.js.org/docs/en/manipulate/add).

2022-09-26 08:37 UTC, kasperg commented on src/components/reservation/reservation-modal.tsx
> +  const [selectedInterest, setSelectedInterest] = useState<string | null>(null);
This is probably where we want to ensure that the interest day is a number not a string.

2022-09-26 08:37 UTC, kasperg commented on src/components/reservation/forms/ModalReservationFormSelect.tsx
> +  items: { label: string; value: string }[];
:+1: Nice refactor.

2022-09-27 07:56 UTC, kasperg approved these changes
:+1: LGTM

2022-09-27 08:40 UTC, sinejespersen approved these changes

2022-09-27 08:40 UTC, merged