Bump stylelint-prettier to latest version
danskernesdigitalebibliotek/dpl-react pull request #1612
Opened 2024-12-27 18:48 UTC by Adamik10

#### Link to issue
https://reload.atlassian.net/browse/DDFBRA-301

#### Description
-

#### Screenshot of the result
-

#### Additional comments or questions
-

2025-01-06 10:32 UTC, ThomasGross requested changes
Some change request. But very nice! 

Please try to remove som of the unnecessary new lines. 😊

2025-01-06 10:32 UTC, ThomasGross commented on src/apps/material-search/MaterialSearch.stories.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/apps/search-header/search-header.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/autosuggest-category/autosuggest-category.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/autosuggest-material/autosuggest-material.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/autosuggest-material/autosuggest-material.tsx
> +            {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/autosuggest-text/autosuggest-text-item.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/autosuggest-text/autosuggest-text-item.tsx
> +          {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/autosuggest/autosuggest.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/autosuggest/autosuggest.tsx
> +        {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/find-on-shelf/FindOnShelfModal.stories.tsx
> +        {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/material/ReviewInfomedia.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/search-bar/search-bar.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/search-bar/search-bar.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/components/search-bar/search-bar.tsx
> +      {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/core/utils/helpers/url.ts
> +    console.log(err);
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/core/utils/modal.tsx
> +        {}
```suggestion
```

2025-01-06 10:32 UTC, ThomasGross commented on src/core/utils/modal.tsx
> +        {}
```suggestion

```

2025-01-06 12:36 UTC, Adamik10 commented on src/core/utils/helpers/url.ts
> +    console.log(err);
This needs to stay, otherwise out Eslint isn't happy 😢

2025-01-07 14:10 UTC, Adamik10 commented
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1631

2025-01-07 14:10 UTC, closed without merging