Exclude blacklistBranches in AvailabilityLabel + FindOnShelfModal
danskernesdigitalebibliotek/dpl-react pull request #190
Opened 2022-10-10 12:47 UTC by kasperbirch1

#### https://reload.atlassian.net/browse/DDFSOEG-250

#### This PR Exclude blacklistBranches in  AvailabilityLabel + FindOnShelfModal
Because blacklisted branches must not be included in the AvailabilityLabel or FindOnShelfModal accessibility check

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

2022-10-11 16:12 UTC, spaceo reviewed
Looks good!
Have one sugesstion...

2022-10-11 16:12 UTC, spaceo commented on src/components/reservation/UserListItems.tsx
> +  }
Could this go into a function in the helper called: `getPickupModalBranches()`?

2022-10-11 16:12 UTC, spaceo commented on src/components/find-on-shelf/FindOnShelfModal.tsx
> +    ...(Array.isArray(blacklistBranches) ? { exclude: blacklistBranches } : {})
simple and concise 👍

2022-10-12 10:45 UTC, kasperg requested changes

2022-10-12 10:45 UTC, kasperg commented on src/apps/material/material.dev.tsx
> +    },
Please add seperate configuration for pickup and availability branches.

There are actually 3 different configurations for the different parts of the system that needs to be blacklisted.

2022-10-21 06:38 UTC, kasperg requested changes
There are a few unnecessary array checks and then we have the continuous `withConfig()` saga for the tests.

Otherwise LGTM.

2022-10-21 06:38 UTC, kasperg commented on src/components/availability-label/availability-label.tsx
> +    });
With the latest changes to `useConfig()`, `blacklistBranches` should always return an array of strings so either there is no need for this `Array.isArray()` check or the check should be different - e.g. checking for the length if we only want to pass the `exclude` parameter if there are any blacklisted branches configured.

2022-10-21 06:38 UTC, kasperg commented on src/components/availability-label/availability-label.tsx
> +export const AvailabilityLabel: React.FC<AvailabilityLabelProps> = withConfig(
🤔 I am still no sure whether this is the right place to add this. Have you tried updating the story to `component: withConfig(AvailabilityLabel)` instead?

If we cannot figure this out then perhaps we could leave this as is, merge it and talk to Mikkel about it on monday.

2022-10-21 06:38 UTC, kasperg commented on src/components/material/periodical/MaterialPeriodical.tsx
> +    ...(Array.isArray(blacklistBranches) ? { exclude: blacklistBranches } : {})
Note the superfluous `isArray()` check here.

2022-10-23 18:38 UTC, sinejespersen approved these changes

2022-10-24 08:20 UTC, merged