Fix publication year
danskernesdigitalebibliotek/dpl-react pull request #221
Opened 2022-11-11 15:29 UTC by kasperbirch1

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2022-11-13 17:28 UTC, spaceo commented on src/core/utils/helpers/general.ts
> +    getFirstPublishedManifestation(manifestations)?.edition?.publicationYear
I think we could make a function called getManifestationPublicationYear that receives a manifestation and returns: `string | null`
So: 

```ts
getManifestationPublicationYear(manifestation: Manifestation): string | null
```
I am not fan og the long optional chaining and by having it done in one place, we only need to change that function if/when it changes again.

2022-11-13 17:40 UTC, spaceo requested changes
I think we need to centralize the way of resolving the publication date of a manifestation

2022-11-14 07:32 UTC, spaceo approved these changes

2022-11-14 08:05 UTC, sinejespersen approved these changes

2022-11-14 08:48 UTC, merged