Update getWorkDescriptionListData + Run codegen:dbc:gateway
danskernesdigitalebibliotek/dpl-react pull request #319
Opened 2023-01-19 10:43 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DSC-23

#### This pull request updates the function getWorkDescriptionListData to include the following changes:

- Modifications to the order of fields.
- Updates to certain fields to contain the desired data.

##### Additionally, the following changes have been made:
- Removal of the hostPublication field and the publisher will now be obtained directly from the manifestation.
- Run codegen:dbc:gateway to update these changes.

**fixtures**:
Reflect the change in the hostPublication field being swapped with the publisher.

**ManifestationsSimple' GraphQL fragment**:

Add the bestRepresentation field to serve as a fallback option for the 'getWorkDescriptionListData' query in cases where no 'currentManifestation' is available.

**'getWorkManifestation' function**:

Updated to accept a type parameter, allowing for the selection of either 'bestRepresentation' or 'latest' representation.

#### Screenshot of the result

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

2023-01-23 15:04 UTC, spaceo commented on src/apps/material/helper.ts
> +  if (type === "bestRepresentation") {
I think we could create an object const for bestRepresentation" and "latest" globally.
And then it should be possible to make a type of it as well.
Maybe the iidiom could be called ManifestationType?

2023-01-23 15:06 UTC, spaceo commented on src/apps/material/helper.ts
>    return work.manifestations.latest as Manifestation;
Isn't it simple just to return:
```typescript
return work.manifestations[type];
```

2023-01-23 15:06 UTC, spaceo commented on src/apps/material/helper.ts
> +    "bestRepresentation"
Please look at comment above about having a global entity describing the manifestation type

2023-01-23 15:12 UTC, spaceo commented on src/apps/material/helper.ts
> +        ),
Please create a function for this:
```typescript
const getPlayingTime = (manifestation: Manifestation) => {
  return String(manifestation?.physicalDescriptions?.[0]?.playingTime ?? "");
}
```
and then use it like:
```typescript
getPlayingTime(manifestation) || getPlayingTime(fallBackManifestation)

2023-01-23 15:12 UTC, spaceo commented on src/apps/material/helper.ts
> +        (fallBackManifestation?.edition?.summary ?? ""),
Please see previous comment

2023-01-23 15:17 UTC, spaceo requested changes
Looks good. I have some remarks though

2023-01-23 15:17 UTC, spaceo commented on src/apps/material/helper.ts
> +
Please see previous comment

2023-01-23 15:17 UTC, spaceo commented on src/apps/material/helper.ts
> +      value: titles?.original?.[0] ?? "",
Could we make a function for this? `getWorkTitle()`?

2023-01-23 15:17 UTC, spaceo commented on src/apps/material/helper.ts
> +        (fallBackManifestation?.publisher.join(" / ") ?? ""),
Please see previous comment about using functions for this

2023-01-23 15:17 UTC, spaceo commented on src/apps/material/helper.ts
> +      value: String(workYear?.year ?? t("unknownText")),
Both text identifiers are pretty generic, especially "unknownText". Could the be prefixd with the context?
Please remember to put them in the proptypes of the app.

2023-01-23 15:17 UTC, spaceo commented on src/apps/material/helper.ts
> +        (fallBackManifestation?.materialTypes?.[0].specific ?? ""),
See previous comment about functions

2023-01-23 15:17 UTC, spaceo commented on src/apps/material/material.tsx
> +      const workManifestation = getWorkManifestation(work, "latest");
See previous comment about manifestation type

2023-01-26 10:58 UTC, Adamik10 reviewed
LGTM 👍 
The only comment I have is that I think the fixtures are unnecessarily long. I normally just delete parts that are not necessary for the tests so the files aren't giant.

2023-01-30 13:21 UTC, spaceo approved these changes
LGTM :+1

2023-01-31 08:06 UTC, jeppekroghitk approved these changes

2023-01-31 08:24 UTC, merged