5627: move pager
danskernesdigitalebibliotek/dpl-react pull request #332
Opened 2023-01-26 13:00 UTC by sinejespersen

#### Link to issue

https://platform.dandigbib.org/issues/5627

#### Description

Move pager so it is not inside the ul

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-01-27 07:33 UTC, jeppekroghitk approved these changes

2023-01-27 14:01 UTC, spaceo requested changes
Looks good. Please look at my comment

2023-01-27 14:01 UTC, spaceo commented on src/apps/reservation-list/list/reservation-list-pagination.test.ts
> +    cy.get("[data-cy='list-reservation-container']")
Please use [cy.getBySel](https://github.com/danskernesdigitalebibliotek/dpl-react/blob/1bcccbc610b229fbe1dbe97c33d4624396e653b5/docs/code_guidelines.md#test-structuring)
 everywhere in this file ;)

2023-01-30 12:44 UTC, spaceo approved these changes
LGTM :+1

2023-01-31 08:00 UTC, merged