Fix/blocked user
danskernesdigitalebibliotek/dpl-react pull request #343
Opened 2023-02-02 12:49 UTC by Adamik10

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-401

#### Description
This PR adds functionality to show disabled reservation button on the material page to blocked users. 

#### Screenshot of the result
If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist
- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions
n/a

2023-02-06 11:09 UTC, kasperg requested changes
:+1: Nice with the added test but please reconsider the checking logic.

2023-02-06 15:04 UTC, Adamik10 commented on src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
> +  return <MaterialButtonUserBlocked size={size} dataCy={dataCy} />;
I can't believe I was overcomplicating it for myself so much.

2023-02-08 08:17 UTC, kasperg approved these changes
:+1: but please remember to remove the unneeded type before you pass this along.

2023-02-08 08:17 UTC, kasperg commented on src/core/utils/types/error.ts
> +};
Please remove this type. It is no longer used.

2023-02-09 13:48 UTC, jeppekroghitk approved these changes
LGTM :)

2023-02-22 13:35 UTC, merged