Feature/menu functionality
danskernesdigitalebibliotek/dpl-react pull request #353
Opened 2023-02-14 08:56 UTC by jeppekroghitk

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-02-15 17:30 UTC, spaceo commented on src/apps/menu/menu.tsx
> +          {!isLoggedIn && (
You can use [userIsAnonymous()](https://github.com/reload/dpl-react/blob/ead79b9764d29c711df2cba4b43661d08fc27c62/src/core/utils/helpers/user.ts#L3) to determine if the the user is authenticated.

2023-02-15 17:31 UTC, spaceo commented on src/apps/menu/menu.tsx
> +                  <div className="avatar bg-global-secondary">
Modal header is very generic. Would it be more precise to mention that is has something to do with the menu?

2023-02-15 17:35 UTC, spaceo requested changes
Looks good. Have some minor remarks.

2023-02-15 17:35 UTC, spaceo commented on src/apps/menu/menu.tsx
> +                  className="link-tag modal-header__link color-secondary-gray"
I think the component is way too long. Couldn't it be seperated into eg.: menuHeader, authenticatedUserMenu, anonymousUserMenu?

2023-02-15 17:35 UTC, spaceo commented on src/apps/menu/menu-not-logged-in/menu-not-logged-in.tsx
> +  closeLoanerMenu: () => void;
We use "patron" instead of "loaner" in the rest of the application.

2023-02-16 12:42 UTC, spaceo commented on src/apps/menu/menu-not-logged-in/menu-not-logged-in.tsx
> +          </button>
I think you should use the `<Button />` component here

2023-02-16 12:44 UTC, spaceo approved these changes
LGTM 👍

2023-02-20 11:13 UTC, sinejespersen commented on src/apps/menu/menu-not-logged-in/menu-not-logged-in.tsx
> +            label={`${t("menuLoginText")}`}
```suggestion
            label={t("menuLoginText")}
```

2023-02-20 11:14 UTC, sinejespersen approved these changes

2023-02-20 11:40 UTC, merged