small accessibility fixes
danskernesdigitalebibliotek/dpl-react pull request #354
Opened 2023-02-14 14:42 UTC by sinejespersen

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-02-23 13:36 UTC, spaceo requested changes
Splendid. Just a few remarks.

2023-02-23 13:36 UTC, spaceo commented on src/apps/patron-page/sections/PincodeSection.tsx
> +  const pincodeLengthMax = parseInt(config("pincodeLengthMaxConfig"), 10) || 4;
The length should be stored in config if it is not configurable by the cms

2023-02-23 13:36 UTC, spaceo commented on src/apps/patron-page/sections/ReservationDetailsSection.tsx
> +        selected={false}
Is this `false` on purpose?

2023-03-06 11:51 UTC, sinejespersen commented on src/apps/patron-page/sections/ReservationDetailsSection.tsx
> +        selected={false}
Yes

2023-03-07 10:58 UTC, spaceo commented on src/apps/patron-page/sections/ReservationDetailsSection.tsx
> +        selected={false}
👍

2023-03-07 10:59 UTC, spaceo commented
LGTM 👍

2023-03-07 11:00 UTC, spaceo approved these changes

2023-03-07 11:05 UTC, merged