Refactor `usePager` to accept a PagerProps object + ad 'isLoading'
danskernesdigitalebibliotek/dpl-react pull request #378
Opened 2023-03-06 10:52 UTC by kasperbirch1

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-03-10 08:05 UTC, kasperg requested changes
Please reconsider how this handles loading using a separate state or React Query.

Otherwise :+1:  and nice cleanup.

2023-03-10 08:05 UTC, kasperg commented on src/apps/search-result/search-result.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
Please consider if we really need a separate loading state.

As I see it this is already provided by React Query and `useSearchWithPaginationQuery`. I do not understand why we need a separate value.

2023-03-10 08:05 UTC, kasperg commented on src/apps/search-result/search-result.entry.tsx
> -  addMoreFiltersText: string;
:+1: for fixing the alphabetical order 🧹 .

2023-03-10 12:40 UTC, kasperg approved these changes
:+1: LGTM

2023-03-14 08:17 UTC, jeppekroghitk approved these changes

2023-03-14 08:56 UTC, merged