Add 'aria-pressed' attribute to `AvailabilityLabel`
danskernesdigitalebibliotek/dpl-react pull request #383
Opened 2023-03-09 10:01 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-449

#### Add 'aria-pressed' attribute to AvailabilityLabel

The aria-pressed attribute has been added to the AvailabilityLabel component in the availability-label.tsx file. The selected prop is used to determine the value of the aria-pressed attribute. Additionally, two Cypress tests have been added to ensure that the aria-pressed attribute is correctly set for both selected and unselected availability labels.

Changes Made:
- Added aria-pressed attribute to the AvailabilityLabel component
- Added two Cypress tests to ensure correct behavior of aria-pressed attribute

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

2023-03-20 08:22 UTC, Adamik10 approved these changes
Very nice. Great that you're testing it as well!

2023-03-20 10:21 UTC, kasperg requested changes
:+1: for adding the test.

Please reconsider the changes based on the bug report.

2023-03-20 10:21 UTC, kasperg commented on src/components/availability-label/availability-label.tsx
>        <img className={classes.check} src={CheckIcon} alt="check-icon" />
Considering this bug report I think two more changes are needed:

1. The `alt` attribute for the `CheckIcon` should be removed. It is included in the screen reader output as shown by the bug report and it is currently not translatable. Any information which could be provided using the icon is better represented through `aria-pressed` so we might as well remove it entirely.
2. The original change and the change in 1. must be reflected in the design system which also have a story for selected availability labels.

2023-03-20 10:21 UTC, kasperg commented on src/apps/material/material.test.ts
> +  it("Check if selected availability label have aria-pressed=true", () => {
```suggestion
  it("Has a selected availability label based on url parameter", () => {
```

2023-03-20 10:21 UTC, kasperg commented on src/apps/material/material.test.ts
> +  it("Check if unselected availability label have aria-pressed=false", () => {
```suggestion
  it("Does not have selected availability labels which does not match url parameter", () => {
```

2023-03-22 08:07 UTC, closed without merging

2023-03-22 08:07 UTC, kasperbirch1 commented
This will be fixed in https://github.com/danskernesdigitalebibliotek/dpl-react/pull/385