add `useKeyPress` hook and modifying the `Modal` to close with 'Escape'
danskernesdigitalebibliotek/dpl-react pull request #389
Opened 2023-03-13 12:15 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-453

#### Description

The `useKeyPress` hook listens for keydown events on the window object and executes a callback function when a specified key is pressed. The Modal component now uses the `useKeyPress` hook to listen for the 'Escape' key and use that to close the modal

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

2023-03-14 08:11 UTC, kasperg requested changes

2023-03-14 08:11 UTC, kasperg commented on src/core/utils/useKeyPress.ts
Please replace this implementation with the hooks provided by [`react-use`](https://github.com/streamich/react-use).

They have a few different options. I encourage you to try them out in their storybook to see the difference and choose accordingly.

2023-03-14 08:11 UTC, kasperg commented on src/core/utils/modal.tsx
> +    if (index >= 0 && modalIds[index] === modalId) {
Please reconsider this code. 

I appreciate the intention in the comment but I do not understand the implementation. If `const index = modalIds.indexOf(modalId)` then I cannot see when `modalIds[index] === modalId` would not be true. If that is the case then it is only a test for `index >= 0`. I had expected a test for whether the modal id was the last entry in the array.

2023-03-16 10:50 UTC, kasperg approved these changes
:+1: but please consider additional commentary.

2023-03-16 10:50 UTC, kasperg commented on src/core/mount.js
> +
```suggestion
function init() {
  // We only want to close the single last modal when the user hits escape.
  // Consequently we only want a single event listener. We cannot guarantee this
  // on the app (or component) level as a page may contain multiple apps. 
  // init provides a single entry point for loading all apps and is suitable for our
  // purpose.
  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") {
      store.dispatch(closeLastModal());
    }
  });

```

We agree on the solution but I think this change warrants some documentation/inline code comment about why it is needed and why it is placed at this level in the codebase.

2023-03-17 14:12 UTC, jeppekroghitk approved these changes

2023-03-17 14:17 UTC, merged