making loan list and reservation list box arrows clickable
danskernesdigitalebibliotek/dpl-react pull request #398
Opened 2023-03-21 12:26 UTC by jeppekroghitk

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-03-23 14:13 UTC, spaceo commented on src/apps/reservation-list/reservation-material/reservation-status.tsx
> +      </button>
Hello reusable arrow button! 😄

2023-03-23 14:14 UTC, spaceo requested changes
Looks good!
Please look at my suggestions.

2023-03-27 07:41 UTC, sinejespersen approved these changes

2023-03-29 11:28 UTC, spaceo approved these changes
LGTM 👍

2023-03-30 06:39 UTC, merged