Improve Screen Reader Accessibility + Add TypeScript helper Function `invalidSwitchCase`
danskernesdigitalebibliotek/dpl-react pull request #408
Opened 2023-03-27 10:57 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-435
https://reload.atlassian.net/browse/DDFSOEG-439
https://reload.atlassian.net/browse/DDFSOEG-443

#### Description
This pull request includes several improvements to enhance accessibility for users who rely on screen readers, as well as adding a TypeScript helper function named `invalidSwitchCase`. 

The primary changes are as follows:

- Added two translation functions, `getFacetFieldTranslation` and `getReservationModalTypeTranslation`, which utilize the `invalidSwitchCase` helper function to ensure all cases are covered in a switch function.

- Updated various elements with appropriate translations for their 'aria-label' attributes and other relevant places.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

2023-03-29 06:45 UTC, kasperg approved these changes
:+1: LGTM

2023-03-29 06:45 UTC, kasperg commented on src/components/facet-line/FacetLineFilters.tsx
> +                ariaLabel={t(`facet${upperFirst(name)}Text`)}
This creates a tricky situation for managing translations as the code does not expose any information about what strings we can expect. This also shows by the fact that no facet translation controls are added in Storybook.

As I see it the possible facet names are limited by [the `FacetField` enumeration](https://github.com/reload/dpl-react/blob/main/src/core/dbc-gateway/generated/graphql.tsx#L306-L306). 


If you want to take a stab at it consider creating a function for generating translations for facet names and use TypeScript to ensure that all values are covered and translations are explicit but I do not think it is necessary to move this PR along.

2023-03-29 06:45 UTC, kasperg commented on src/components/reservation/forms/ModalReservationFormSelect.tsx
> +    `screenReaderModalDescription${upperFirst(type)}Text`
See comment about regarding dynamically generated translation strings. This case and the rest of this PR is not so bad though.

2023-03-29 06:45 UTC, kasperg commented on src/apps/material/material.entry.tsx
> +  orderDigitalCopyModalScreenReaderModalDescriptionText: string;
:+1: for cleanup.

2023-04-17 06:47 UTC, kasperg requested changes

2023-04-17 06:47 UTC, kasperg commented on src/components/facet-browser/helper.ts
> +export const getFacetFieldTranslation = (name: string): string => {
As far as I can tell this addition needs some more work and should not be merged as is.

2023-04-19 08:03 UTC, sinejespersen approved these changes

2023-04-19 08:33 UTC, kasperg approved these changes
:+1: LGTM

2023-04-19 08:34 UTC, merged