Fix/digital copy access
danskernesdigitalebibliotek/dpl-react pull request #456
Opened 2023-05-19 09:12 UTC by Adamik10

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-303

#### Description
Similarly to #441 this PR fixes an access issue for users that aren't living in the same municipality as the library they are currently browsing. In this case it is in regards to the digital articles.

#### Screenshot of the result
n/a

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions
dad2db0e09592ae2b9dc1e92417ea6d10112bcf0 is the only commit that needs to be reviewed. Rest belongs to #441

+ this PR needs to be merged in after #441

2023-05-22 15:03 UTC, spaceo requested changes
Great implementation! I have some remarks...

2023-05-22 15:03 UTC, spaceo commented on src/components/material/material-buttons/online/MaterialButtonOnlineDigitalArticle.tsx
> +  });
Didn't you talk with Kasper about creating a hook for fetching Patron data if user is logged in? Would make sense to use it here as well.

I think you should also create a function alongside the other user functions called ìsResident()` that looks at the `resident` property of the `Patron` object. We probably need it in other places in the future.

2023-05-25 13:18 UTC, spaceo reviewed
Great! One comment...

2023-05-25 13:25 UTC, spaceo commented
Also there is a dear old Cypress test that is failing...

2023-05-30 07:37 UTC, Adamik10 commented on src/components/material/material-buttons/online/MaterialButtonOnlineInfomediaArticle.tsx
> +
Why is that? usePatronData() hook is asynchronous after all 🤔

2023-05-30 08:37 UTC, spaceo approved these changes
LGTM 👍

2023-05-31 09:00 UTC, merged