Add inline tests for facet-browser helper functions
danskernesdigitalebibliotek/dpl-react pull request #494
Opened 2023-06-15 11:21 UTC by kasperbirch1

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-06-16 10:01 UTC, spaceo requested changes
Great addition! But I think the snapshots should be moved to separate snapshot files.
Could they reside either in a folder next to the file called "snapshots" or inside the unit test dir also in a folder called "snapshots"?

2023-06-20 14:43 UTC, spaceo requested changes
There is a problem with the snapshot paths. They are not unique enough.

2023-06-26 07:50 UTC, spaceo approved these changes

2023-06-27 07:32 UTC, sinejespersen approved these changes

2023-08-31 12:32 UTC, merged