Added a formatdatetime for displaying the time aswell
danskernesdigitalebibliotek/dpl-react pull request #513
Opened 2023-08-09 07:31 UTC by jeppekroghitk

#### Link to issue

[Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5892)

#### Description

Reservation expiration time until now only shown as date. This PR introduces the time as well.

#### Screenshot of the result

<img width="1794" alt="Screenshot 2023-08-09 at 09 31 46" src="https://github.com/danskernesdigitalebibliotek/dpl-react/assets/106669866/4a032340-a166-4f8c-aa16-70b0b6e57e34">

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-08-09 13:56 UTC, kasperg requested changes
Code looks good but tests are failing due to changes in this PR. Please fix these.

2023-08-11 06:52 UTC, kasperg approved these changes
:+1: LGTM

2023-08-11 11:46 UTC, yepzdk approved these changes

2023-08-11 11:46 UTC, yepzdk commented on src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
> +      .should("have.text", "Your reservation expires 27-01-2023 22:37!");
Is the exclamation mark at the end by design ?
Seems unnecessary.

2023-08-11 11:57 UTC, merged