Move material button reservable from another library
danskernesdigitalebibliotek/dpl-react pull request #797
Opened 2023-12-20 10:15 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-528

#### Description

This pull request refactors the order buttons by moving the logic for displaying the `MaterialButtonReservableFromAnotherLibrary` component and refactoring the `getReservablePidsFromAnotherLibrary` function into a `useReservableFromAnotherLibrary` hook. That also checks if the material is not reservable and should be ordered via openOrder.

#### Screenshot of the result

2023-12-20 10:35 UTC, spaceo requested changes
Looks good. But I think it is a bad idea to delete tests without adding new

2023-12-20 10:35 UTC, spaceo commented on src/core/utils/useReservableFromAnotherLibrary.tsx
> +const useReservableFromAnotherLibrary = (manifestations: Manifestation[]) => {
Great with the hook.
I think tou should add some tests testing the hook now that you have deleted the old tests.

2024-01-02 10:05 UTC, spaceo approved these changes
LGTM 👍

2024-01-03 07:51 UTC, kasperg commented
@spaceo already gave this a :+1: :smile:

2024-01-11 07:31 UTC, merged